delete:
  user: ${random.value}
  password: ${random.value}
network:
  map:
    testnet:
      max-node-number: 10
      min-node-number: 2
      lease-days: 5
    ffweimar:
      max-node-number: 1000
      min-node-number: 2
      lease-days: 90
spring:
  jackson:
    serialization:
      indent_output: true
  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:REG;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
  boot:
    admin:
      url: http://localhost:8090
management:
  security:
    enabled: false